#!/usr/bin/env bash
# this script installs and configures nginx web server, adds a custom Nginx response header

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo sh -c 'echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;
	
	add_header X-Served-By \$hostname;

        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
	
        server_name _;

        location / {
                try_files \$uri \$uri/ =404;
        }
}" > /etc/nginx/sites-available/default'

sudo nginx -t
sudo service nginx restart
