#!/usr/bin/env bash
# install haproxy
SETUP="frontend http-in
	bind *:80
	default_backend servers
backend servers
	balance roundrobin
	server 266761-web-01 100.25.165.191:80 check
	server 266761-web-02 3.83.245.148:80 check
"
apt-get -y update
apt-get -y install haproxy
echo "$SETUP" >> /etc/haproxy/haproxy.cfg
service haproxy restart
