#!/usr/bin/env bash
# Print 24 hours of a day

k=0
l=0
while ((k < 24)); do
	echo Hour: $k
	l=0
	while ((l < 60)); do
		if ((l < 10)); then
			echo 0$l
		else
			echo $l
		fi
		l=$((l+1))
	done
	k=$((k+1))
done
