#!/usr/bin/env bash
# Print 24 hours of a day

i=0
j=0
while ((i < 24)); do
	echo Hour: $i
	j=0
	while ((j < 60)); do
		if ((j < 10)); then
			echo 0$j
		else
			echo $j
		fi
		j=$((j+1))
	done
	i=$((i+1))
done
