#!/usr/bin/env bash
# This script connects to the server using SSH with a private key.

# Use ssh with the -i flag to specify the
# private key file and the target user@host.
ssh -i ~/.ssh/school ubuntu@54.237.54.19
